openapi: "3.0.0"
info:
  version: 1.0.0
  title: Crowdforce
  license:
    name: Apache License, Version 2.0
servers:
  - url: http://api.crowdforce.space/v1
paths:
  /projects:
    get:
      summary: Projects are filtered by space.
      operationId: projects
      parameters:
        - name: space
          in: query
          deprecated:
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projects"
        default:
          description: Space is required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"





components:
  schemas:


    Project:

    Projects:

    Activity:

    Activities:

    Space:

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    City:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
