/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.activities_id_seq</code>
     */
    public static final Sequence<Integer> ACTIVITIES_ID_SEQ = Internal.createSequence("activities_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.goals_id_seq</code>
     */
    public static final Sequence<Integer> GOALS_ID_SEQ = Internal.createSequence("goals_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.projects_id_seq</code>
     */
    public static final Sequence<Integer> PROJECTS_ID_SEQ = Internal.createSequence("projects_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.users_id_seq</code>
     */
    public static final Sequence<Integer> USERS_ID_SEQ = Internal.createSequence("users_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
