/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model;


import space.crowdforce.model.tables.Activities;
import space.crowdforce.model.tables.ActivityParticipants;
import space.crowdforce.model.tables.FlywaySchemaHistory;
import space.crowdforce.model.tables.Goals;
import space.crowdforce.model.tables.ProjectSubscribers;
import space.crowdforce.model.tables.Projects;
import space.crowdforce.model.tables.TrackableItem;
import space.crowdforce.model.tables.TrackableItemEvent;
import space.crowdforce.model.tables.TrackableItemEventParticipants;
import space.crowdforce.model.tables.TrackableItemEventPrototype;
import space.crowdforce.model.tables.TrackableItemParticipants;
import space.crowdforce.model.tables.Users;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.activities</code>.
     */
    public static final Activities ACTIVITIES = Activities.ACTIVITIES;

    /**
     * The table <code>public.activity_participants</code>.
     */
    public static final ActivityParticipants ACTIVITY_PARTICIPANTS = ActivityParticipants.ACTIVITY_PARTICIPANTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.goals</code>.
     */
    public static final Goals GOALS = Goals.GOALS;

    /**
     * The table <code>public.project_subscribers</code>.
     */
    public static final ProjectSubscribers PROJECT_SUBSCRIBERS = ProjectSubscribers.PROJECT_SUBSCRIBERS;

    /**
     * The table <code>public.projects</code>.
     */
    public static final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>public.trackable_item</code>.
     */
    public static final TrackableItem TRACKABLE_ITEM = TrackableItem.TRACKABLE_ITEM;

    /**
     * The table <code>public.trackable_item_event</code>.
     */
    public static final TrackableItemEvent TRACKABLE_ITEM_EVENT = TrackableItemEvent.TRACKABLE_ITEM_EVENT;

    /**
     * The table <code>public.trackable_item_event_participants</code>.
     */
    public static final TrackableItemEventParticipants TRACKABLE_ITEM_EVENT_PARTICIPANTS = TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS;

    /**
     * The table <code>public.trackable_item_event_prototype</code>.
     */
    public static final TrackableItemEventPrototype TRACKABLE_ITEM_EVENT_PROTOTYPE = TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE;

    /**
     * The table <code>public.trackable_item_participants</code>.
     */
    public static final TrackableItemParticipants TRACKABLE_ITEM_PARTICIPANTS = TrackableItemParticipants.TRACKABLE_ITEM_PARTICIPANTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
