/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model;


import space.crowdforce.model.tables.Activities;
import space.crowdforce.model.tables.ActivityParticipants;
import space.crowdforce.model.tables.FlywaySchemaHistory;
import space.crowdforce.model.tables.Goals;
import space.crowdforce.model.tables.ProjectSubscribers;
import space.crowdforce.model.tables.Projects;
import space.crowdforce.model.tables.Users;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.activities</code>.
     */
    public static final Activities ACTIVITIES = Activities.ACTIVITIES;

    /**
     * The table <code>public.activity_participants</code>.
     */
    public static final ActivityParticipants ACTIVITY_PARTICIPANTS = ActivityParticipants.ACTIVITY_PARTICIPANTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.goals</code>.
     */
    public static final Goals GOALS = Goals.GOALS;

    /**
     * The table <code>public.project_subscribers</code>.
     */
    public static final ProjectSubscribers PROJECT_SUBSCRIBERS = ProjectSubscribers.PROJECT_SUBSCRIBERS;

    /**
     * The table <code>public.projects</code>.
     */
    public static final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
