/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import space.crowdforce.model.Keys;
import space.crowdforce.model.Public;
import space.crowdforce.model.tables.records.TrackableItemEventParticipantsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemEventParticipants extends TableImpl<TrackableItemEventParticipantsRecord> {

    private static final long serialVersionUID = 1036360978;

    /**
     * The reference instance of <code>public.trackable_item_event_participants</code>
     */
    public static final TrackableItemEventParticipants TRACKABLE_ITEM_EVENT_PARTICIPANTS = new TrackableItemEventParticipants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackableItemEventParticipantsRecord> getRecordType() {
        return TrackableItemEventParticipantsRecord.class;
    }

    /**
     * The column <code>public.trackable_item_event_participants.id</code>.
     */
    public final TableField<TrackableItemEventParticipantsRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('trackable_item_event_participants_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.trackable_item_event_participants.trackable_item_event_id</code>.
     */
    public final TableField<TrackableItemEventParticipantsRecord, Integer> TRACKABLE_ITEM_EVENT_ID = createField(DSL.name("trackable_item_event_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.trackable_item_event_participants.user_id</code>.
     */
    public final TableField<TrackableItemEventParticipantsRecord, Integer> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.trackable_item_event_participants.creation_time</code>.
     */
    public final TableField<TrackableItemEventParticipantsRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.trackable_item_event_participants.last_update_time</code>.
     */
    public final TableField<TrackableItemEventParticipantsRecord, LocalDateTime> LAST_UPDATE_TIME = createField(DSL.name("last_update_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.trackable_item_event_participants.confirmed</code>.
     */
    public final TableField<TrackableItemEventParticipantsRecord, Integer> CONFIRMED = createField(DSL.name("confirmed"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.trackable_item_event_participants</code> table reference
     */
    public TrackableItemEventParticipants() {
        this(DSL.name("trackable_item_event_participants"), null);
    }

    /**
     * Create an aliased <code>public.trackable_item_event_participants</code> table reference
     */
    public TrackableItemEventParticipants(String alias) {
        this(DSL.name(alias), TRACKABLE_ITEM_EVENT_PARTICIPANTS);
    }

    /**
     * Create an aliased <code>public.trackable_item_event_participants</code> table reference
     */
    public TrackableItemEventParticipants(Name alias) {
        this(alias, TRACKABLE_ITEM_EVENT_PARTICIPANTS);
    }

    private TrackableItemEventParticipants(Name alias, Table<TrackableItemEventParticipantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrackableItemEventParticipants(Name alias, Table<TrackableItemEventParticipantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TrackableItemEventParticipants(Table<O> child, ForeignKey<O, TrackableItemEventParticipantsRecord> key) {
        super(child, key, TRACKABLE_ITEM_EVENT_PARTICIPANTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<TrackableItemEventParticipantsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TRACKABLE_ITEM_EVENT_PARTICIPANTS;
    }

    @Override
    public UniqueKey<TrackableItemEventParticipantsRecord> getPrimaryKey() {
        return Keys.TRACKABLE_ITEM_EVENT_PARTICIPANTS_PKEY;
    }

    @Override
    public List<UniqueKey<TrackableItemEventParticipantsRecord>> getKeys() {
        return Arrays.<UniqueKey<TrackableItemEventParticipantsRecord>>asList(Keys.TRACKABLE_ITEM_EVENT_PARTICIPANTS_PKEY);
    }

    @Override
    public List<ForeignKey<TrackableItemEventParticipantsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TrackableItemEventParticipantsRecord, ?>>asList(Keys.TRACKABLE_ITEM_EVENT_PARTICIPANTS__TRACKABLE_ITEM_EVENT_PARTICIPANTS_TRACKABLE_ITEM_EVENT_ID_FKEY, Keys.TRACKABLE_ITEM_EVENT_PARTICIPANTS__TRACKABLE_ITEM_EVENT_PARTICIPANTS_USER_ID_FKEY);
    }

    public TrackableItemEvent trackableItemEvent() {
        return new TrackableItemEvent(this, Keys.TRACKABLE_ITEM_EVENT_PARTICIPANTS__TRACKABLE_ITEM_EVENT_PARTICIPANTS_TRACKABLE_ITEM_EVENT_ID_FKEY);
    }

    public Users users() {
        return new Users(this, Keys.TRACKABLE_ITEM_EVENT_PARTICIPANTS__TRACKABLE_ITEM_EVENT_PARTICIPANTS_USER_ID_FKEY);
    }

    @Override
    public TrackableItemEventParticipants as(String alias) {
        return new TrackableItemEventParticipants(DSL.name(alias), this);
    }

    @Override
    public TrackableItemEventParticipants as(Name alias) {
        return new TrackableItemEventParticipants(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackableItemEventParticipants rename(String name) {
        return new TrackableItemEventParticipants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackableItemEventParticipants rename(Name name) {
        return new TrackableItemEventParticipants(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
