/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import space.crowdforce.model.tables.ActivityParticipants;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityParticipantsRecord extends TableRecordImpl<ActivityParticipantsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 914003036;

    /**
     * Setter for <code>public.activity_participants.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activity_participants.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.activity_participants.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activity_participants.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ActivityParticipants.ACTIVITY_PARTICIPANTS.ACTIVITY_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ActivityParticipants.ACTIVITY_PARTICIPANTS.USER_ID;
    }

    @Override
    public Integer component1() {
        return getActivityId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getActivityId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public ActivityParticipantsRecord value1(Integer value) {
        setActivityId(value);
        return this;
    }

    @Override
    public ActivityParticipantsRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ActivityParticipantsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityParticipantsRecord
     */
    public ActivityParticipantsRecord() {
        super(ActivityParticipants.ACTIVITY_PARTICIPANTS);
    }

    /**
     * Create a detached, initialised ActivityParticipantsRecord
     */
    public ActivityParticipantsRecord(Integer activityId, Integer userId) {
        super(ActivityParticipants.ACTIVITY_PARTICIPANTS);

        set(0, activityId);
        set(1, userId);
    }
}
