/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.Activities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitiesRecord extends UpdatableRecordImpl<ActivitiesRecord> implements Record7<Integer, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = -1121905065;

    /**
     * Setter for <code>public.activities.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activities.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.activities.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activities.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.activities.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.activities.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.activities.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.activities.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.activities.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.activities.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.activities.end_time</code>.
     */
    public void setEndTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.activities.end_time</code>.
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.activities.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.activities.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Activities.ACTIVITIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Activities.ACTIVITIES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Activities.ACTIVITIES.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Activities.ACTIVITIES.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Activities.ACTIVITIES.START_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Activities.ACTIVITIES.END_TIME;
    }

    @Override
    public Field<Integer> field7() {
        return Activities.ACTIVITIES.PROJECT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getStartTime();
    }

    @Override
    public LocalDateTime component6() {
        return getEndTime();
    }

    @Override
    public Integer component7() {
        return getProjectId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getStartTime();
    }

    @Override
    public LocalDateTime value6() {
        return getEndTime();
    }

    @Override
    public Integer value7() {
        return getProjectId();
    }

    @Override
    public ActivitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ActivitiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ActivitiesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ActivitiesRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ActivitiesRecord value5(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public ActivitiesRecord value6(LocalDateTime value) {
        setEndTime(value);
        return this;
    }

    @Override
    public ActivitiesRecord value7(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public ActivitiesRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivitiesRecord
     */
    public ActivitiesRecord() {
        super(Activities.ACTIVITIES);
    }

    /**
     * Create a detached, initialised ActivitiesRecord
     */
    public ActivitiesRecord(Integer id, String name, String description, LocalDateTime creationTime, LocalDateTime startTime, LocalDateTime endTime, Integer projectId) {
        super(Activities.ACTIVITIES);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, creationTime);
        set(4, startTime);
        set(5, endTime);
        set(6, projectId);
    }
}
