/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.Goals;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoalsRecord extends UpdatableRecordImpl<GoalsRecord> implements Record6<Integer, String, String, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = -374755964;

    /**
     * Setter for <code>public.goals.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.goals.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.goals.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.goals.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.goals.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.goals.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.goals.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.goals.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.goals.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.goals.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.goals.progress_bar</code>.
     */
    public void setProgressBar(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.goals.progress_bar</code>.
     */
    public Integer getProgressBar() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Goals.GOALS.ID;
    }

    @Override
    public Field<String> field2() {
        return Goals.GOALS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Goals.GOALS.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Goals.GOALS.CREATION_TIME;
    }

    @Override
    public Field<Integer> field5() {
        return Goals.GOALS.PROJECT_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Goals.GOALS.PROGRESS_BAR;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public Integer component5() {
        return getProjectId();
    }

    @Override
    public Integer component6() {
        return getProgressBar();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public Integer value5() {
        return getProjectId();
    }

    @Override
    public Integer value6() {
        return getProgressBar();
    }

    @Override
    public GoalsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GoalsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GoalsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GoalsRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public GoalsRecord value5(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public GoalsRecord value6(Integer value) {
        setProgressBar(value);
        return this;
    }

    @Override
    public GoalsRecord values(Integer value1, String value2, String value3, LocalDateTime value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoalsRecord
     */
    public GoalsRecord() {
        super(Goals.GOALS);
    }

    /**
     * Create a detached, initialised GoalsRecord
     */
    public GoalsRecord(Integer id, String name, String description, LocalDateTime creationTime, Integer projectId, Integer progressBar) {
        super(Goals.GOALS);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, creationTime);
        set(4, projectId);
        set(5, progressBar);
    }
}
