/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import space.crowdforce.model.tables.ProjectSubscribers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectSubscribersRecord extends TableRecordImpl<ProjectSubscribersRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 963292142;

    /**
     * Setter for <code>public.project_subscribers.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project_subscribers.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.project_subscribers.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project_subscribers.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProjectSubscribers.PROJECT_SUBSCRIBERS.PROJECT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ProjectSubscribers.PROJECT_SUBSCRIBERS.USER_ID;
    }

    @Override
    public Integer component1() {
        return getProjectId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getProjectId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public ProjectSubscribersRecord value1(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public ProjectSubscribersRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ProjectSubscribersRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectSubscribersRecord
     */
    public ProjectSubscribersRecord() {
        super(ProjectSubscribers.PROJECT_SUBSCRIBERS);
    }

    /**
     * Create a detached, initialised ProjectSubscribersRecord
     */
    public ProjectSubscribersRecord(Integer projectId, Integer userId) {
        super(ProjectSubscribers.PROJECT_SUBSCRIBERS);

        set(0, projectId);
        set(1, userId);
    }
}
