/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.jooq.geo.PGPoint;
import space.crowdforce.model.tables.Projects;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectsRecord extends UpdatableRecordImpl<ProjectsRecord> implements Record6<Integer, String, PGPoint, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = -591546440;

    /**
     * Setter for <code>public.projects.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.projects.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.projects.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.projects.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.projects.location</code>.
     */
    public void setLocation(PGPoint value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.projects.location</code>.
     */
    public PGPoint getLocation() {
        return (PGPoint) get(2);
    }

    /**
     * Setter for <code>public.projects.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.projects.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.projects.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.projects.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.projects.owner_id</code>.
     */
    public void setOwnerId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.projects.owner_id</code>.
     */
    public Integer getOwnerId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, PGPoint, String, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, PGPoint, String, LocalDateTime, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Projects.PROJECTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Projects.PROJECTS.NAME;
    }

    @Override
    public Field<PGPoint> field3() {
        return Projects.PROJECTS.LOCATION;
    }

    @Override
    public Field<String> field4() {
        return Projects.PROJECTS.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Projects.PROJECTS.CREATION_TIME;
    }

    @Override
    public Field<Integer> field6() {
        return Projects.PROJECTS.OWNER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public PGPoint component3() {
        return getLocation();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreationTime();
    }

    @Override
    public Integer component6() {
        return getOwnerId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public PGPoint value3() {
        return getLocation();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreationTime();
    }

    @Override
    public Integer value6() {
        return getOwnerId();
    }

    @Override
    public ProjectsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectsRecord value3(PGPoint value) {
        setLocation(value);
        return this;
    }

    @Override
    public ProjectsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProjectsRecord value5(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProjectsRecord value6(Integer value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public ProjectsRecord values(Integer value1, String value2, PGPoint value3, String value4, LocalDateTime value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectsRecord
     */
    public ProjectsRecord() {
        super(Projects.PROJECTS);
    }

    /**
     * Create a detached, initialised ProjectsRecord
     */
    public ProjectsRecord(Integer id, String name, PGPoint location, String description, LocalDateTime creationTime, Integer ownerId) {
        super(Projects.PROJECTS);

        set(0, id);
        set(1, name);
        set(2, location);
        set(3, description);
        set(4, creationTime);
        set(5, ownerId);
    }
}
