/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.TrackableItemEventPrototype;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemEventPrototypeRecord extends UpdatableRecordImpl<TrackableItemEventPrototypeRecord> implements Record6<Integer, String, LocalDateTime, String, Integer, Integer> {

    private static final long serialVersionUID = -170209685;

    /**
     * Setter for <code>public.trackable_item_event_prototype.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_prototype.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.trackable_item_event_prototype.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_prototype.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trackable_item_event_prototype.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_prototype.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.trackable_item_event_prototype.recurring</code>.
     */
    public void setRecurring(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_prototype.recurring</code>.
     */
    public String getRecurring() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.trackable_item_event_prototype.trackable_item_id</code>.
     */
    public void setTrackableItemId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_prototype.trackable_item_id</code>.
     */
    public Integer getTrackableItemId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.trackable_item_event_prototype.participants_number</code>.
     */
    public void setParticipantsNumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_prototype.participants_number</code>.
     */
    public Integer getParticipantsNumber() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, LocalDateTime, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, LocalDateTime, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE.MESSAGE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE.START_TIME;
    }

    @Override
    public Field<String> field4() {
        return TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE.RECURRING;
    }

    @Override
    public Field<Integer> field5() {
        return TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE.TRACKABLE_ITEM_ID;
    }

    @Override
    public Field<Integer> field6() {
        return TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE.PARTICIPANTS_NUMBER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public LocalDateTime component3() {
        return getStartTime();
    }

    @Override
    public String component4() {
        return getRecurring();
    }

    @Override
    public Integer component5() {
        return getTrackableItemId();
    }

    @Override
    public Integer component6() {
        return getParticipantsNumber();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public LocalDateTime value3() {
        return getStartTime();
    }

    @Override
    public String value4() {
        return getRecurring();
    }

    @Override
    public Integer value5() {
        return getTrackableItemId();
    }

    @Override
    public Integer value6() {
        return getParticipantsNumber();
    }

    @Override
    public TrackableItemEventPrototypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrackableItemEventPrototypeRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TrackableItemEventPrototypeRecord value3(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public TrackableItemEventPrototypeRecord value4(String value) {
        setRecurring(value);
        return this;
    }

    @Override
    public TrackableItemEventPrototypeRecord value5(Integer value) {
        setTrackableItemId(value);
        return this;
    }

    @Override
    public TrackableItemEventPrototypeRecord value6(Integer value) {
        setParticipantsNumber(value);
        return this;
    }

    @Override
    public TrackableItemEventPrototypeRecord values(Integer value1, String value2, LocalDateTime value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackableItemEventPrototypeRecord
     */
    public TrackableItemEventPrototypeRecord() {
        super(TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE);
    }

    /**
     * Create a detached, initialised TrackableItemEventPrototypeRecord
     */
    public TrackableItemEventPrototypeRecord(Integer id, String message, LocalDateTime startTime, String recurring, Integer trackableItemId, Integer participantsNumber) {
        super(TrackableItemEventPrototype.TRACKABLE_ITEM_EVENT_PROTOTYPE);

        set(0, id);
        set(1, message);
        set(2, startTime);
        set(3, recurring);
        set(4, trackableItemId);
        set(5, participantsNumber);
    }
}
