/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.TrackableItem;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemRecord extends UpdatableRecordImpl<TrackableItemRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -1700833313;

    /**
     * Setter for <code>public.trackable_item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackable_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.trackable_item.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackable_item.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trackable_item.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trackable_item.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TrackableItem.TRACKABLE_ITEM.ID;
    }

    @Override
    public Field<String> field2() {
        return TrackableItem.TRACKABLE_ITEM.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return TrackableItem.TRACKABLE_ITEM.ACTIVITY_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getActivityId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getActivityId();
    }

    @Override
    public TrackableItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrackableItemRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TrackableItemRecord value3(Integer value) {
        setActivityId(value);
        return this;
    }

    @Override
    public TrackableItemRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackableItemRecord
     */
    public TrackableItemRecord() {
        super(TrackableItem.TRACKABLE_ITEM);
    }

    /**
     * Create a detached, initialised TrackableItemRecord
     */
    public TrackableItemRecord(Integer id, String name, Integer activityId) {
        super(TrackableItem.TRACKABLE_ITEM);

        set(0, id);
        set(1, name);
        set(2, activityId);
    }
}
