/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.TrackableItemEvent;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemEventRecord extends UpdatableRecordImpl<TrackableItemEventRecord> implements Record7<Integer, String, Integer, Integer, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = -781829235;

    /**
     * Setter for <code>public.trackable_item_event.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.trackable_item_event.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trackable_item_event.trackable_item_id</code>.
     */
    public void setTrackableItemId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.trackable_item_id</code>.
     */
    public Integer getTrackableItemId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.trackable_item_event.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.trackable_item_event.event_time</code>.
     */
    public void setEventTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.event_time</code>.
     */
    public LocalDateTime getEventTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.trackable_item_event.confirmation_time</code>.
     */
    public void setConfirmationTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.confirmation_time</code>.
     */
    public LocalDateTime getConfirmationTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.trackable_item_event.confirmed</code>.
     */
    public void setConfirmed(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.confirmed</code>.
     */
    public Integer getConfirmed() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, Integer, Integer, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, Integer, Integer, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.ID;
    }

    @Override
    public Field<String> field2() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.MESSAGE;
    }

    @Override
    public Field<Integer> field3() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.TRACKABLE_ITEM_ID;
    }

    @Override
    public Field<Integer> field4() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.EVENT_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.CONFIRMATION_TIME;
    }

    @Override
    public Field<Integer> field7() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.CONFIRMED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public Integer component3() {
        return getTrackableItemId();
    }

    @Override
    public Integer component4() {
        return getUserId();
    }

    @Override
    public LocalDateTime component5() {
        return getEventTime();
    }

    @Override
    public LocalDateTime component6() {
        return getConfirmationTime();
    }

    @Override
    public Integer component7() {
        return getConfirmed();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public Integer value3() {
        return getTrackableItemId();
    }

    @Override
    public Integer value4() {
        return getUserId();
    }

    @Override
    public LocalDateTime value5() {
        return getEventTime();
    }

    @Override
    public LocalDateTime value6() {
        return getConfirmationTime();
    }

    @Override
    public Integer value7() {
        return getConfirmed();
    }

    @Override
    public TrackableItemEventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value3(Integer value) {
        setTrackableItemId(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value5(LocalDateTime value) {
        setEventTime(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value6(LocalDateTime value) {
        setConfirmationTime(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value7(Integer value) {
        setConfirmed(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord values(Integer value1, String value2, Integer value3, Integer value4, LocalDateTime value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackableItemEventRecord
     */
    public TrackableItemEventRecord() {
        super(TrackableItemEvent.TRACKABLE_ITEM_EVENT);
    }

    /**
     * Create a detached, initialised TrackableItemEventRecord
     */
    public TrackableItemEventRecord(Integer id, String message, Integer trackableItemId, Integer userId, LocalDateTime eventTime, LocalDateTime confirmationTime, Integer confirmed) {
        super(TrackableItemEvent.TRACKABLE_ITEM_EVENT);

        set(0, id);
        set(1, message);
        set(2, trackableItemId);
        set(3, userId);
        set(4, eventTime);
        set(5, confirmationTime);
        set(6, confirmed);
    }
}
