/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import space.crowdforce.model.tables.TrackableItemParticipants;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemParticipantsRecord extends TableRecordImpl<TrackableItemParticipantsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 923321569;

    /**
     * Setter for <code>public.trackable_item_participants.trackable_item_id</code>.
     */
    public void setTrackableItemId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackable_item_participants.trackable_item_id</code>.
     */
    public Integer getTrackableItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.trackable_item_participants.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackable_item_participants.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TrackableItemParticipants.TRACKABLE_ITEM_PARTICIPANTS.TRACKABLE_ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TrackableItemParticipants.TRACKABLE_ITEM_PARTICIPANTS.USER_ID;
    }

    @Override
    public Integer component1() {
        return getTrackableItemId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getTrackableItemId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public TrackableItemParticipantsRecord value1(Integer value) {
        setTrackableItemId(value);
        return this;
    }

    @Override
    public TrackableItemParticipantsRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TrackableItemParticipantsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackableItemParticipantsRecord
     */
    public TrackableItemParticipantsRecord() {
        super(TrackableItemParticipants.TRACKABLE_ITEM_PARTICIPANTS);
    }

    /**
     * Create a detached, initialised TrackableItemParticipantsRecord
     */
    public TrackableItemParticipantsRecord(Integer trackableItemId, Integer userId) {
        super(TrackableItemParticipants.TRACKABLE_ITEM_PARTICIPANTS);

        set(0, trackableItemId);
        set(1, userId);
    }
}
