/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.TrackableItemEvent;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemEventRecord extends UpdatableRecordImpl<TrackableItemEventRecord> implements Record4<Integer, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = -178055394;

    /**
     * Setter for <code>public.trackable_item_event.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.trackable_item_event.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trackable_item_event.trackable_item_id</code>.
     */
    public void setTrackableItemId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.trackable_item_id</code>.
     */
    public Integer getTrackableItemId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.trackable_item_event.event_time</code>.
     */
    public void setEventTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trackable_item_event.event_time</code>.
     */
    public LocalDateTime getEventTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.ID;
    }

    @Override
    public Field<String> field2() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.MESSAGE;
    }

    @Override
    public Field<Integer> field3() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.TRACKABLE_ITEM_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TrackableItemEvent.TRACKABLE_ITEM_EVENT.EVENT_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public Integer component3() {
        return getTrackableItemId();
    }

    @Override
    public LocalDateTime component4() {
        return getEventTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public Integer value3() {
        return getTrackableItemId();
    }

    @Override
    public LocalDateTime value4() {
        return getEventTime();
    }

    @Override
    public TrackableItemEventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value3(Integer value) {
        setTrackableItemId(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord value4(LocalDateTime value) {
        setEventTime(value);
        return this;
    }

    @Override
    public TrackableItemEventRecord values(Integer value1, String value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackableItemEventRecord
     */
    public TrackableItemEventRecord() {
        super(TrackableItemEvent.TRACKABLE_ITEM_EVENT);
    }

    /**
     * Create a detached, initialised TrackableItemEventRecord
     */
    public TrackableItemEventRecord(Integer id, String message, Integer trackableItemId, LocalDateTime eventTime) {
        super(TrackableItemEvent.TRACKABLE_ITEM_EVENT);

        set(0, id);
        set(1, message);
        set(2, trackableItemId);
        set(3, eventTime);
    }
}
