/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.TrackableItemEventParticipants;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackableItemEventParticipantsRecord extends UpdatableRecordImpl<TrackableItemEventParticipantsRecord> implements Record6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = -705748418;

    /**
     * Setter for <code>public.trackable_item_event_participants.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_participants.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.trackable_item_event_participants.trackable_item_event_id</code>.
     */
    public void setTrackableItemEventId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_participants.trackable_item_event_id</code>.
     */
    public Integer getTrackableItemEventId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.trackable_item_event_participants.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_participants.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.trackable_item_event_participants.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_participants.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.trackable_item_event_participants.last_update_time</code>.
     */
    public void setLastUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_participants.last_update_time</code>.
     */
    public LocalDateTime getLastUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.trackable_item_event_participants.confirmed</code>.
     */
    public void setConfirmed(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trackable_item_event_participants.confirmed</code>.
     */
    public Integer getConfirmed() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS.TRACKABLE_ITEM_EVENT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS.LAST_UPDATE_TIME;
    }

    @Override
    public Field<Integer> field6() {
        return TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS.CONFIRMED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTrackableItemEventId();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getLastUpdateTime();
    }

    @Override
    public Integer component6() {
        return getConfirmed();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTrackableItemEventId();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getLastUpdateTime();
    }

    @Override
    public Integer value6() {
        return getConfirmed();
    }

    @Override
    public TrackableItemEventParticipantsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrackableItemEventParticipantsRecord value2(Integer value) {
        setTrackableItemEventId(value);
        return this;
    }

    @Override
    public TrackableItemEventParticipantsRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TrackableItemEventParticipantsRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public TrackableItemEventParticipantsRecord value5(LocalDateTime value) {
        setLastUpdateTime(value);
        return this;
    }

    @Override
    public TrackableItemEventParticipantsRecord value6(Integer value) {
        setConfirmed(value);
        return this;
    }

    @Override
    public TrackableItemEventParticipantsRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackableItemEventParticipantsRecord
     */
    public TrackableItemEventParticipantsRecord() {
        super(TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS);
    }

    /**
     * Create a detached, initialised TrackableItemEventParticipantsRecord
     */
    public TrackableItemEventParticipantsRecord(Integer id, Integer trackableItemEventId, Integer userId, LocalDateTime creationTime, LocalDateTime lastUpdateTime, Integer confirmed) {
        super(TrackableItemEventParticipants.TRACKABLE_ITEM_EVENT_PARTICIPANTS);

        set(0, id);
        set(1, trackableItemEventId);
        set(2, userId);
        set(3, creationTime);
        set(4, lastUpdateTime);
        set(5, confirmed);
    }
}
