/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record3<Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 522570348;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.users.tg_username</code>.
     */
    public void setTgUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.tg_username</code>.
     */
    public String getTgUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.reg_date</code>.
     */
    public void setRegDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.reg_date</code>.
     */
    public LocalDateTime getRegDate() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.TG_USERNAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Users.USERS.REG_DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTgUsername();
    }

    @Override
    public LocalDateTime component3() {
        return getRegDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTgUsername();
    }

    @Override
    public LocalDateTime value3() {
        return getRegDate();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setTgUsername(value);
        return this;
    }

    @Override
    public UsersRecord value3(LocalDateTime value) {
        setRegDate(value);
        return this;
    }

    @Override
    public UsersRecord values(Integer value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String tgUsername, LocalDateTime regDate) {
        super(Users.USERS);

        set(0, id);
        set(1, tgUsername);
        set(2, regDate);
    }
}
