/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import space.crowdforce.model.tables.UserCodes;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCodesRecord extends TableRecordImpl<UserCodesRecord> implements Record3<Integer, String, LocalDateTime> {

    private static final long serialVersionUID = -25734974;

    /**
     * Setter for <code>public.user_codes.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_codes.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_codes.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_codes.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_codes.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_codes.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserCodes.USER_CODES.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UserCodes.USER_CODES.CODE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return UserCodes.USER_CODES.CREATION_TIME;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTime();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTime();
    }

    @Override
    public UserCodesRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserCodesRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public UserCodesRecord value3(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public UserCodesRecord values(Integer value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserCodesRecord
     */
    public UserCodesRecord() {
        super(UserCodes.USER_CODES);
    }

    /**
     * Create a detached, initialised UserCodesRecord
     */
    public UserCodesRecord(Integer userId, String code, LocalDateTime creationTime) {
        super(UserCodes.USER_CODES);

        set(0, userId);
        set(1, code);
        set(2, creationTime);
    }
}
