/*
 * This file is generated by jOOQ.
 */
package space.crowdforce.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import space.crowdforce.model.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record4<Integer, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = -1183721589;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.tg_id</code>.
     */
    public void setTgId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.tg_id</code>.
     */
    public Integer getTgId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.users.reg_date</code>.
     */
    public void setRegDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.reg_date</code>.
     */
    public LocalDateTime getRegDate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Users.USERS.TG_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Users.USERS.REG_DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getTgId();
    }

    @Override
    public LocalDateTime component4() {
        return getRegDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getTgId();
    }

    @Override
    public LocalDateTime value4() {
        return getRegDate();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UsersRecord value3(Integer value) {
        setTgId(value);
        return this;
    }

    @Override
    public UsersRecord value4(LocalDateTime value) {
        setRegDate(value);
        return this;
    }

    @Override
    public UsersRecord values(Integer value1, String value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, Integer tgId, LocalDateTime regDate) {
        super(Users.USERS);

        set(0, id);
        set(1, name);
        set(2, tgId);
        set(3, regDate);
    }
}
