logging:
  level:
    com.zaxxer.hikari.HikariConfig: debug


management:
  endpoints:
    web:
      exposure:
        include: "health,info"

telegram:
  bot:
    token: ${TOKEN} #"your_telegram_bot_token"

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/crowdforce
    username: ${DB_USER}
    password: ${DB_PASSWORD}