logging:
  level:
    com.zaxxer.hikari.HikariConfig: debug


management:
  endpoints:
    web:
      exposure:
        include: "health,info"

telegram:
  bot:
    token: "1319279698:AAFZzsg5gF1m7wMGAklD4ZtGbEouCQptfkw" #"your_telegram_bot_token"
    username: "crowdforce_bot"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crowdforce
    username: crowdforce
    password: crowdforce