name: Deploy master branch to VPS

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build project package
        run: mvn -B clean package --file pom.xml

      - name: Verify artifacts
        run: mvn -B clean verify --file pom.xml

      - name: Move JAR to TEMP dir
        run: mkdir artifacts && mv cf-app/target/*.jar artifacts/app.jar

      - name: List artifacts
        run: ls -laH artifacts

      - name: Push to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CF_PROD_SERVER_IP }}
          username: ${{ secrets.CF_PROD_SERVER_USER }}
          password: ${{ secrets.CF_PROD_SERVER_PASS }}
          source: "artifacts/app.jar"
          target: "/opt/crowdforce/"

      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CF_PROD_SERVER_IP }}
          username: ${{ secrets.CF_PROD_SERVER_USER }}
          password: ${{ secrets.CF_PROD_SERVER_PASS }}
          script: |
            sudo systemctl restart crowdforce-app.service
            sudo systemctl status crowdforce-app.service

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cf-artifact
          path: artifacts/app.jar
